//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public decimal ssn { get; set; }
        public int age { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int Movie { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string img { get; set; }
    }
}
