//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.TimeSpan duration { get; set; }
        public string lang { get; set; }
        public string caption { get; set; }
        public string genre { get; set; }
        public System.DateTime vision_date { get; set; }
        public int Director { get; set; }
        public string img { get; set; }
        public Nullable<int> idForWeb { get; set; }
    }
}
