//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saloon
    {
        public int Room_id { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> Double_Bed { get; set; }
        public Nullable<int> Single_Bed { get; set; }
        public Nullable<int> Vibrating_Seat { get; set; }
        public string Snack { get; set; }
        public string Sound_System { get; set; }
        public decimal Screen_Size_inch_ { get; set; }
        public int CinemaID { get; set; }        

        public virtual Cinemas Cinemas { get; set; }
    }
}
